module.exports = {
    "KNOT_EN_US" : {
        "overhand knot": "Tie an overhand knot, or basic knot, by taking both ends of the rope in your hand.  First cross the right end over the left to make a loop.  Then pass the end under the loop to form a knot.  After making the basic knot, pull it tight on both ends.",
        "square knot": "Tie a square knot by taking both ends of the rope in your hand.  Begin with passing the right end over the left end and forming an overhand knot.  Next take the same end, now on the left, back over the right end and through for a second loop.  After pulling the ends tight you should have two sides that are flat and even, with both sides forming a loop with the strings passing through together.  A good way to remember this knot is: Right over left, left over right, makes a square knot, good and tight.",
        "granny knot": "A granny knot is similar to a square knot, but use the same side for both steps. If you start with the right end for the first overhand knot, use the new right end again for the second loop.  After pulling the ends tight the sides should have both sides forming a loop but with one string above the loop and one string below the loop.  You know you made a granny knot by remembering: Right over left, right over left, looks like a square knot but it's a mess.",
        "two half-hitches": "Two half-hitches should be tied around something like a post or tent stake.  You will use only the short end of the rope to tie it, and leave the long end alone. Start by looping the rope around the post with the short end in one hand. Make a half-hitch by looping around the long end of the rope and pulling it snug.  Then make the second half-hitch by looping around the long end of the rope again, on the outside of your first hitch.  You will know you tied it right when you can pull on the long end of the rope and the knot tightens but does not come loose.",
        "taut-line hitch": "A taut-line hitch is useful for tying around something that you will want to tighten or loosen afterward.  You will only use the short end of the rope, and leave the long end loose or connected to something like a tarp before tying the hitch.  Begin by looping around the post and passing the short end of the rope around the long end twice.  You don't need to make it too tight yet, and will want enough left-over rope to tie a third hitch on the outside of the first two.  After making the three half-hitches, two inside and one outside, you can pull the hitches snug and adjust the entire knot up or down the long end.",
        "bowline": "Tying a bowline can be difficult, but with practice it is very useful and secure.  There are a few methods to try, but my favorite is to hold the rope with a long end and short end in in each hand.  Take the short end over the long end, and while still holding the rope, pass your entire hand under the long end and back out making a small loop around your hand.  Finally, pass the short piece of rope around the long end above the loop and back through the same loop.  If you tied it correctly, you should be able to pull the ends tight and the bowline should not slip or move.  Practice going over, under, around, and through - to make a bowline true and true.",
        "sheet bend": "A sheet bend is great for joining two ropes together, and works even better with a thick and thin rope.  First, make a bend in the thicker rope and hold it steady.  Next take the thinner rope through the loop from underneath and around the outside off the bend.  Go around both sides of the bend, starting on the top of one side, going underneath, and crossing back to the top on the other side.  Finally pass the short end back across the top of the bend, going under your thinner rope but not going back through the bend.  After you tighten the knot, you should be able to pull on either rope firmly without coming loose.",
        "slip knot": "A slip knot can be surprisingly versitile.  Start by making one loop in your rope, then make a second loop and pull it up through the first loop.  If the loop comes undone, you probably passed your second loop through backwards.  Try again while switching which side of the first loop you pull through.  You can pull a slip knot tight or you can make multiple chains of loops to form a chain of slip knots.",
        "clove hitch": "The clove hitch is useful when you want to wrap around a post but not adjust or tighten it afterward.  Start by looping around the post twice and forming an X with your rope.  Then pass the short end underneath the two loops, through the middle of the X, but be careful to avoid crossing the long end.  Fishish tying the clove hitch by pulling tightly.  If the post you are tying to has one end open, you can make the two loops on your fingers and slide the knot over the top of the post afterward for a quicker solution.",
        "timber hitch": "A timber hitch is useful when tying a rope around a medium to large post or log. Start with the short end of the rope and wrap it around the log.  Next loop the short around the long end once, then wrap backward up the short end again three or four times.  You should have a sliding hitch that tightens when you pull on the long end, but can be loosened easily if there is no tension.  For large logs you may need to wrap more often.",
        "knot knot joke": "Can you tie a knot? I cannot. Ah so you CAN knot? No. I cannot knot. Not knot? Who's there? POOH! Pooh who? No! You'll need more than two knots. Not possible. Ah, so it is possible to knot those two pieces. Not these pieces! Yes. Knot those pieces. Why not? Because it's all for naught! - from Winnie the Pooh - 2011. IMDb number tt1449283."
    }
};
